### ISSUE TITLE
Metrics discovery agent should use hostname from nats-tls link

### ISSUE THREAD

**Issue by aminjam** [cloudfoundry/metrics-discovery-release#8]
### Summary
Currently it looks like metrics-discovery-registrar job (for linux and windows) is using `nats.service.cf.internal` as [it's host](https://github.com/cloudfoundry/metrics-discovery-release/blob/b252c9c6876da971f71ef2b7595ff85ca57d95fc/jobs/metrics-discovery-registrar/templates/bpm.yml.erb#L2). This alias is configurable in [bosh manifest](https://github.com/cloudfoundry/cf-deployment/blob/3ba20341c7431ace178f8b12d44c470738db1326/cf-deployment.yml#L379). 

### Potential Solution
Instead of using the hardcoded value, the job can pull in this information [from the bosh links](https://github.com/cloudfoundry/diego-release/commit/44260f2401c346dd2d5f73e9587fd88c2b86007e).

**Comment by heycait** [comment]
Would you mind making a PR for this?

**Comment by aminjam** [comment]
I am not planning on submitting a PR for this issue.

**Comment by louis-brann** [comment]
This was resolved by https://github.com/cloudfoundry/metrics-discovery-release/pull/7
